services:
  app1:
    image: banking-monolith-app
    ports:
      - "8081:8082"
  app2:
    image: banking-monolith-app
    ports:
      - "8082:8082"
  app3:
    image: banking-monolith-app
    ports:
      - "8083:8082"
